### ISSUE TITLE
多级目录

### ISSUE THREAD

**Issue by JackyAndroid** [Merlin218/vuepress-plugin-auto-navbar#1]
多级目录支持吗
比如 5、6 级的目录结构
dir1
+ dir2
++ dir3
+++ dir4
++++ dir5

**Comment by Merlin218** [comment]
> 

理论上是应该是支持无限层级的，但需要考虑vupress或主题是否支持更深层级的展示

**Comment by Merlin218** [comment]
> 多级目录支持吗 比如 5、6 级的目录结构 dir1
> 
> * dir2
>   ++ dir3
>   +++ dir4
>   ++++ dir5

理论上应该是支持无限层级的目录配置生成，但要考虑vuepress或主题是否支持更深目录层级的展示。
